### ISSUE TITLE
Include in akka-http-play-json

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http-marshallers#7]
Let's include `play-json` support in this repo.

Currently there are two impls:
- https://github.com/hseeberger/akka-http-json
- https://github.com/guillaumebreton/play-json-support

Let's discuss here on how to standardize on one of those and include the maintainers into the team.

// cc @guillaumebreton @hseeberger

**Comment by hseeberger** [comment]
From a quick look at @guillaumebreton's project it looks like he mimicked the existing (previously in akka-http RC2, now in this project) code for spray. I think that's a good idea, hence I suggest to move this code and just drop mine (which also contains support for spray which no has become obsolete).

**Comment by hseeberger** [comment]
For the record, I think we should aim for Play JSON 2.4(-RC-x), but that's probably a different issue/ticket later.

**Comment by ktoso** [comment]
Yes, targetting Play `2.4-[RC...]` is good here, since Akka-Http is also in RC phase now

**Comment by guillaumebreton** [comment]
I will create a PR for this tonight and move the code here and upgrade the dependency to play 2.4-RC

**Comment by hseeberger** [comment]
Sounds great, because @guillaumebreton has all the work ;-)

**Comment by ktoso** [comment]
We have discussed again on this subject, and due to various dependencies between project we currently figured that `akka-http-play-json` must live outside of akka. 

Reasons that lead to this decision:
- We can not move the spray marshallers out of akka/akka without increasing the build's complexity a lot.
- We can not include play-json in akka/akka because of circular dependencies
- We do want to support spray, play marshallers. However since there is an active community project by @guillaumebreton we leave this effort to you to lead this. In case customers may need help with play-json we will of course help out, as play is part of our supported stack. We'll cross that bridge once we get to it though.

This also means we'll delete this (akka-http-marshallers) repository, as it serves no purpose.
We welcome others in the community to build various marshallers and would like them to keep them in their own repositories.
